### ISSUE TITLE
Does the operator support Single Step Instrumentation?

### ISSUE THREAD

**Issue by joshfrench** [DataDog/datadog-operator#1030]
I see that the basic [Helm chart](https://github.com/DataDog/helm-charts/tree/main/charts/datadog#enabling-apm-single-step-instrumentation-beta) supports [Single Step Instrumentation](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/single-step-apm/?tab=kubernetes) but I don't see a corresponding option in the operator chart. Is there a way to enable this while using the operator?

Thanks!

**Comment by CharlyF** [comment]
Hey @joshfrench - Thanks for reaching out. We worked on that https://github.com/DataDog/datadog-operator/pull/981 but had to delay to contribution due to some namespace considerations. Now that this is dealt with we are going to be resuming the work and we are targeting the next version of the Operator for this feature (we are starting the QA on Jan 5th).

**Comment by levan-m** [comment]
This is planned in Operator 1.5.0
PR https://github.com/DataDog/datadog-operator/pull/1031
