### ISSUE TITLE
Feature Request: Allow specifying to not create the datadog-agent service account

### ISSUE THREAD

**Issue by exicx** [DataDog/datadog-operator#1127]
We are using IRSA to allow datadog-agent to get secrets from AWS Secrets Manager using the CSI Secret Provider driver.
We have to "grant" datadog-agent permissions to secrets manager by annotating the datadog-agent service account with the role arn for CSI secret provider to use.

Datadog-operator is overwriting the datadog-agent service account and removing the annotation, and breaking the agent because it can no longer access secrets manager secrets (used to store our dd api/app key).

We would like this operator to be configured to not create the service account, and instead told what service account to use (by name) to the datadog-agent daemonset.

Similarly to the idiom in helm charts:

```
serviceaccount:
  create: false
  name: <name of sa to use instead of making one>
```

**Comment by tbavelier** [comment]
@exicx 
If I'm understanding correctly your issue, this feature is already somewhat present with the combination of `[key].createRbac` and `[key].serviceAccountName` (https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md) that you would use as overrides such as in my manifest below : 
```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    [...]
  override:
    nodeAgent:
      serviceAccountName: my-annotated-sa
      createRbac: false
```

Here is an example in my environment : 
<img width="661" alt="image" src="https://github.com/DataDog/datadog-operator/assets/97530782/ef9bffa2-2e61-4ed8-903e-d8c449cac240">
As you can see, my service account has none of the labels from being managed by the Operator : its lifecycle is independent from the `DatadogAgent` custom resource and will keep its annotations.

**However**, the caveat is that you need to manage RBAC yourself (due to `createRbac: false`) : I'd recommend copying the clusterrole / clusterrolebinding / role / rolebinding with `datadog` ensuring they target the desired SA.

Would that work for you ?
