### ISSUE TITLE
Mention required token for cluster agent

### ISSUE THREAD

**Issue by jketcham** [DataDog/datadog-operator#191]
I just installed the datadog-operator into a cluster and for the most part the process was pretty straightforward, nice work on this!

However I did run into an issue getting the cluster-agent working: I didn't set a 'secret token' anywhere for the cluster-agent to use, which caused a `CreateContainerConfigError` error to throw from the cluster-agent complaining that `secret "datadog" not found`. I didn't realize it at first after reading through the installation/getting started docs, but a token is required and can be set in a secret called 'datadog' ([as mentioned here](https://docs.datadoghq.com/agent/cluster_agent/setup/?tab=secret#step-2---secure-cluster-agent-to-agent-communication)), or it can be set in the in `spec.credentials.token` field of the `DatadogAgent` config. Currently, I see that it is shown in [this example with the cluster agent](https://github.com/DataDog/datadog-operator/blob/master/examples/datadog-agent-with-clusteragent.yaml#L9), but not in [the 'all' example](https://github.com/DataDog/datadog-operator/blob/master/examples/datadog-agent-all.yaml). I feel like having to set this token should be called out more explicitly in the docs.

Separately, I did think it was kind of odd that the `api_key` and the `app_key` can be configured through the `DatadogAgent` to get the value from a secret (instead of setting the plain text value in the config), but the `token` [can only be set plainly in the config](https://github.com/DataDog/datadog-operator/blob/v0.4.0/config/crd/bases/v1/datadoghq.com_datadogagents.yaml#L7765) and can't be fetched from a secret. Was that intentional? That functionality might be nice too, so I could potentially just have one secret with my api/app keys and token for the cluster-agent.

**Comment by L3n41c** [comment]
Hello @jketcham,

In fact, as the `token` is used only to secure communications between the node agents and the cluster agent which are both managed by the operator, the operator is able to automatically generate a random `token` and to put it in an operator-managed secret if none is provided.

There is currently a bug in the operator where it doesn’t create the operator-managed secret if there’s only the `token` to put, because the API and the APP key are shipped in user-supplied secrets.

This bug will be fixed by #190.

**Comment by jketcham** [comment]
Ahh ok makes sense @L3n41c, thanks for the info!
