### ISSUE TITLE
Add support for admission controller failure policy

### ISSUE THREAD

**Issue by jcogilvie** [DataDog/datadog-operator#632]
**Describe what you expected:**
I would like to use the operator to configure the [admissionController's failurePolicy](https://github.com/DataDog/helm-charts/pull/579/files) but it doesn't seem to be included in the agent CRD spec.

**Additional environment details (Operating System, Cloud provider, etc):**
EKS 1.22

**Comment by khewonc** [comment]
Hi, I'll add a card to our backlog to add that field to the operator. Since the failure policy is a cluster agent env var based on that PR you linked, you can get the same behavior by adding the `DD_ADMISSION_CONTROLLER_FAILURE_POLICY` env var to the cluster agent using `clusterAgent.config.env`: https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v1alpha1.md

**Comment by khewonc** [comment]
Apologies for the delay on this! It should be possible to configure the `failurePolicy` for the admission controller starting in v1.0.0 of the operator using the v2alpha1 CRD: https://github.com/DataDog/datadog-operator/blob/480f69931540a7de1808ffd7bd9b5043c1249fe7/apis/datadoghq/v2alpha1/datadogagent_types.go#L474
