### ISSUE TITLE
Operator has a 200 goroutine limit

### ISSUE THREAD

**Issue by cspargo** [DataDog/datadog-operator#666]
**Output of the info page (if this is a bug)**

this seems to be any version

**Describe what happened:**

if the operator uses more than 200 goroutines, the healthz check fails causing liveness probe failure and it goes into a crashloop. I happened to trigger this by setting `WATCH_NAMESPACE` to be more than one namespace (`WATCH_NAMESPACE=datadog,default`)

The healthz handler is here https://github.com/DataDog/datadog-operator/blob/6369a83b2103bf620ed387256cb1d8381fcb5500/main.go#L210
and the maximum is constant set here to 200 https://github.com/DataDog/datadog-operator/blob/6369a83b2103bf620ed387256cb1d8381fcb5500/main.go#L44

If I curl the health endpoint inside the container, I get
```
healthz check failed
[-]goroutines-number failed: reason withheld
```

**Describe what you expected:**

I expect the operator to be able to handle a valid configuration without exceeding this limit and getting killed. Is the limit necessary? If not, can it be removed? If yes, can it be configurable?

**Steps to reproduce the issue:**

I happened to trigger this by setting `WATCH_NAMESPACE` to be more than one namespace (`WATCH_NAMESPACE=datadog,default`) but it may require other settings to reach this number of goroutines, not sure.

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by CharlyF** [comment]
Hey @cspargo - Thanks for opening this up, I ran into this a few weeks ago when using the conversion webhook so it's good to know that there are other ways to trigger the issue.
This is in our check list of must fix to GA the version 1.0 and I am not sure which solution we are going to adopt but we will keep you posted here.
Out of curiosity, which version of the operator are you using?

**Comment by cspargo** [comment]
okay thanks. I'm using 0.8.3.

**Comment by miguelaferreira** [comment]
We are using version 0.8.1 and also hitting this issue. Is there anything we could be doing to workaround it?

**Comment by CharlyF** [comment]
Hello all, this has been fixed in the latest Datadog Operator that was GA'ed last week. We bumped the minimum and made it configurable in the command line (and via the helm chart config).

We documented the migration path [here](https://github.com/DataDog/helm-charts/tree/main/charts/datadog-operator#migrating-to-the-version-10-of-the-datadog-operator). It touches on storage versions too, which is now v2alpha stored by default.
I am going to close this issue for now but feel free but let us know if this issue persists, and if you end up migrating feel free to share your feedback, we want to ensure a smooth experience for all of our users.
