### ISSUE TITLE
How to migrate from DaemonSet

### ISSUE THREAD

**Issue by davezuch** [DataDog/datadog-operator#911]
Our Datadog Agent was installed on Kubernetes [manually](https://docs.datadoghq.com/containers/guide/kubernetes_daemonset/) with DaemonSets a couple years ago. I want to upgrade to the Datadog Operator, and am wondering about the best way to go about that.

Can I just install the Operator then uninstall the manual deployments? Are there any considerations to having both running for a period of time?

**Comment by celenechang** [comment]
Hi @davezuch , thanks for reaching out. There may be some conflicts with dependencies such as RBACs created by the Operator. Due to that, if some downtime is tolerable, it may be cleaner to first delete the Agent DaemonSet along with the RBACs created according to the doc you linked (along with any other dependencies that may have been created for Datadog features).

Does that help?

**Comment by davezuch** [comment]
@celenechang yeah that makes sense, thanks for the answer!

**Comment by celenechang** [comment]
Great glad that makes sense, I will close out this issue.
